# Twitter
TWITTER_CONSUMER_KEY: 'SHW1MGRZLfQPwioddtcSXweaa'
TWITTER_CONSUMER_SECRET: 'f046gfVt3SSFbhQHGBOSsba9psLa1fgKPy3eT4JkUCBJFY1Cfq'
TWITTER_ACCESS_TOKEN: '375548813-5wnIL5ZTYjrDRfIx3DESj7zNXpH5s0CPzyLYDTyD'
TWITTER_ACCESS_TOKEN_SECRET: 'ODfleYmnerTrJA3JsVrWTJrg46KZCM7XsXjbcrBSdnKsC'

# mashups admin credentials for password-protected views
MASHUPS_ADMIN_UNAME: 'citizen'
MASHUPS_ADMIN_PASS: 'resist'